# Generated by Django 4.0.3 on 2022-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_food_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
