# Generated by Django 4.0.3 on 2022-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_food_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
