# Generated by Django 4.0.3 on 2022-04-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_food_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='imageUrl',
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohydrates', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('saturatedFat', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.food')),
            ],
        ),
    ]
